# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nextjs-app-ingress
# spec:
#   rules:
#     - host: staging.bms.100xdevs.com
#       http:
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: nextjs-app
#               port:
#                 number: 3000
